// One-time generator: produces lib/fakeUIData.ts with frozen static fake data.
// Run once: `npx tsx scripts/generate-fake-ui-data.ts`
// Do NOT run again — output is checked into the repo and treated as frozen.

import { writeFileSync } from 'fs';
import { join } from 'path';
import {
  generateFakeBarbers,
  generateFakeShops,
  type FakeBarber,
  type FakeShop,
} from '../lib/fakeDataGenerator';

const BARBER_COUNT = 100;
const SHOP_COUNT = 50;

const barbers: FakeBarber[] = generateFakeBarbers(BARBER_COUNT).map(b => ({
  ...b,
  userId: `fake_${b.userId}`,
}));

const shops: FakeShop[] = generateFakeShops(SHOP_COUNT).map(s => ({
  ...s,
  shopId: `fake_${s.shopId}`,
}));

const header = `// AUTO-GENERATED by scripts/generate-fake-ui-data.ts — DO NOT EDIT BY HAND.
// Frozen static fake data for the UI-only fake system.
// Regenerating will invalidate every fake id already shared in URLs/screenshots.

import type { FakeBarber, FakeShop } from './fakeDataGenerator';
`;

const body =
  `\nexport const fakeBarbersUI: FakeBarber[] = ${JSON.stringify(barbers, null, 2)};\n` +
  `\nexport const fakeShopsUI: FakeShop[] = ${JSON.stringify(shops, null, 2)};\n`;

const outPath = join(__dirname, '..', 'lib', 'fakeUIData.ts');
writeFileSync(outPath, header + body, 'utf8');

console.log(`Wrote ${barbers.length} barbers + ${shops.length} shops → ${outPath}`);
